# Generated by Django 6.0 on 2025-12-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_commentactivity_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="statuschangeactivity",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="statuschangeactivity",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="column",
            field=models.CharField(
                choices=[
                    ("todo", "Todo"),
                    ("in_progress", "In Progress"),
                    ("done", "Done"),
                ],
                max_length=20,
            ),
        ),
    ]
