# Generated by Django 6.0 on 2025-12-30 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("tasks", "0003_activity_task_alter_statuschangeactivity_new_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"base_manager_name": "objects"},
        ),
        migrations.AddField(
            model_name="activity",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
