# Generated by Django 6.0 on 2025-12-30 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentactivity",
            options={"verbose_name_plural": "Comment activities"},
        ),
        migrations.AlterModelOptions(
            name="statuschangeactivity",
            options={"verbose_name_plural": "Status change activities"},
        ),
    ]
